const downloadFile = () => {
    const link = document.createElement("a");

    //Role

    const race = document.getElementById("race");
    const race_Race = race.options[race.selectedIndex].text;
    const archetype = document.getElementById("archetype");
    const race_Archetype = archetype.options[archetype.selectedIndex].text;
    const preferredWeapon = document.getElementById("preferredWeapon");
    const race_PreferredWeapon = preferredWeapon.options[preferredWeapon.selectedIndex].text;
    const alignment = document.getElementById("alignment");
    const race_Alignment = alignment.options[alignment.selectedIndex].text;

    //Appearance


    //Personality


    //Birthplace or Home


    //Past


    //Religion


    //Family


    //Sexuality


    const file = new Blob([
        "Role\n",
        "\n",
        "Race → " + race_Race,
        "\nArchetype → " + race_Archetype,
        "\nPreferred Weapon → " + race_PreferredWeapon,
        "\nAlignment → " + race_Alignment,
        "\n\n⚔️Generated by Ethertale⚔️",
        "\nhttps://github.com/Ethertale",
        "\nCredits to AC Arcana for the base"
    ], { type: 'text/plain' });

    link.href = URL.createObjectURL(file);
    link.download = "YourCharacter.txt";
    link.click();
    URL.revokeObjectURL(link.href);
};